#用于部署运行所依赖的服务
version: '3.9'
services:
  # 基础环境组件
  # 1.Alist
  alist:
    build: .
    container_name: alist
    restart: always
    tty: true
    network_mode: bridge
    hostname: alist
    # 配置服务器资源约束。此例子中服务被限制为使用内存不超过800M不低于256M以及cpu不超过0.5（单核的50%）不低于0.1（单核的10%）
    # 经过实际测试，建议不低于200M
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 800M
        reservations:
          cpus: '0.1'
          memory: 256M
    ports:
      - "5244:5244"
    volumes:
      - /etc/alist:/opt/alist/data #配置文件挂载
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      # - DATABASE_URL="postgres://hfhgpvbymdzusj:39d7f6f3ee4288103e382d5dec22ce668c4e5cb65120f64d574b808775674eb4@ec2-3-218-171-44.compute-1.amazonaws.com:5432/d4o07n33pf6ot7"
      - CACHE_EXPIRATION=60
      - CLEANUP_INTERVAL=120
      - ASSETS=/

